# Generated by Django 5.2.7 on 2025-10-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='city_from',
            field=models.CharField(default='Krasnodar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='city_to',
            field=models.CharField(default='Krasnodar'),
            preserve_default=False,
        ),
    ]
