# Generated by Django 5.2.7 on 2025-10-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_train_city_from_train_city_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезды'},
        ),
    ]
